storages:
- name: forward
  box: 
      pose: {x: 10, y: 0, z: 1.3}
      size: {x: 0.1, y: 0.1, z: 0.1}
- name: ground
  box: 
      pose: {x: 1, y: 0, z: 0}
      size: {x: 0.1, y: 0.1, z: 0.1}
- name: viewpoint
  box: 
      pose: {x: 0.5, y: 0, z: 1.4}
      size: {x: 0.1, y: 0.1, z: 0.1}
