
  base_frame_id: base_footprint
  beam_skip_distance: 0.5
  beam_skip_error_threshold: 0.9
  beam_skip_threshold: 0.3
  converge_dist_threshold: 0.5
  do_beamskip: true
  first_map_only: false
  global_frame_id: map
  gui_publish_rate: 5.0
  initial_cov_aa: 8.263216841518012e-05
  initial_cov_xx: 1.8725381465856117e-05
  initial_cov_yy: 0.0001302065688832954
  initial_pose_a: 1.3890942595188593
  initial_pose_x: 10.622148945231952
  initial_pose_y: 12.536167432156994
  kld_err: 0.07
  kld_z: 0.99
  laser_lambda_short: 0.1
  laser_likelihood_max_dist: 2.0
  laser_max_beams: 60
  laser_max_range: -1.0
  laser_min_range: -1.0
  laser_model_type: likelihood_field_prob
  laser_sigma_hit: 0.2
  laser_z_hit: 0.6
  laser_z_max: 0.05
  laser_z_rand: 0.4
  laser_z_short: 0.05
  max_particles: 2500
  min_particles: 350
  odom_alpha1: 0.2
  odom_alpha2: 0.2
  odom_alpha3: 0.2
  odom_alpha4: 0.2
  odom_alpha5: 0.2
  odom_frame_id: odom
  odom_model_type: diff-corrected
  recovery_alpha_fast: 0.0
  recovery_alpha_slow: 0.0
  resample_interval: 1
  restore_defaults: false
  save_pose_rate: -1.0
  tf_broadcast: true
  transform_tolerance: 0.2
  update_min_a: 0.08726646259971647
  update_min_d: 0.1
  use_map_topic: false

