# Settings for both Costmaps
map_type: costmap

global_frame: map
robot_base_frame: base_footprint
robot_radius: 0.275

update_frequency : 5.0
publish_frequency: 5.0

transform_tolerance: 5. # Laptop, should be 0.2

min_obstacle_height: -0.1
max_obstacle_height: 0.4

max_obstacle_range: 5.0
raytrace_range: 10
