# Independent settings for the planner's costmap
global_costmap:

  update_frequency : 5.0
  publish_frequency: 5.0

  #track_unknown_space: true
  #unknown_cost_value : 255

  resolution: 0.1

  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: obstacle_layer
      type: 'costmap_2d::ObstacleLayer'
      #    - name: footprint_layer
      #      type: 'costmap_2d::FootprintLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'

  static_layer:
    enabled  : true
    subscribe_to_updates: true
    map_topic: map

  obstacle_layer:
    enabled: true
    observation_sources: sensor_scan_clf point_cloud_sensor1 point_cloud_sensor0
    #combination_method: 0 # can erase static layer

    point_cloud_sensor0: {sensor_frame: xtion_link, data_type: PointCloud2, topic: /voxel_grid/output, marking: true, clearing: false, min_obstacle_height: 0.05}
    point_cloud_sensor1: {sensor_frame: xtion_link, data_type: PointCloud2, topic: /voxel_grid/output, marking: false, clearing: true, min_obstacle_height: -1.0}



    sensor_scan_clf:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: /scan_clf
      expected_update_rate: 0.2
      #observation_persistence: 1.0
      #inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 15.0
      obstacle_range: 8.0

  #footprint_layer:
  #  enabled: true

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.90
    cost_scaling_factor: 3

### Biron
# commons
#max_obstacle_range: 3.0
#raytrace_range: 5.5

#inflation_radius: 0.90
#update_frequency: 5.0      # default 5.0
#publish_frequency: 5.0      # default 0.0
#cost_scaling_factor: 3.0    # default 10.0
  

