# Independent settings for the local costmap
local_costmap:

  update_frequency : 5.0
  publish_frequency: 2.0

  static_map    : false
  rolling_window: true
  width         : 3.0
  height        : 3.0
  resolution    : 0.05

  observation_sources: sensor_scan_clf

  sensor_scan_clf:
    sensor_frame: base_laser_link
    data_type: LaserScan
    topic: /scan
    expected_update_rate: 1
    observation_persistence: 1.0
    inf_is_valid: true
    marking: true
    clearing: true
    raytrace_range: 9.5
    obstacle_range: 9.0
    min_obstacle_height: -0.1
    max_obstacle_height: 0.4


