#local planner
#base_local_planner: pal_local_planner/PalLocalPlanner
base_local_planner: base_local_planner/TrajectoryPlannerROS
#base_local_planner: dwa_local_planner/DWAPlannerROS


PalLocalPlanner:

  # main params
  acc_lim_x    : 0.3
  acc_lim_theta: !degrees 15.0
  xy_goal_tolerance : 0.2
  yaw_goal_tolerance: 0.2
  obstacle_avoider: 0 # VFH
  use_crowd       : false

  # mcc and oac params
  max_vel_x : &max_vel_x 0.3
  max_rot_vel: !degrees 60.0
  travel_speed_sfl   : *max_vel_x
  point_b_sfl        : 0.26
  decay              : 0.85
  max_dist_plan_ahead: 2.0
  min_dist_plan_ahead: 0.27
  dist_to_final_speed: 1
  
  allow_backwards    : false
  robot_width      : 0.54


### Biron
TrajectoryPlannerROS:

# Set the acc.eleration limits of the robot - "most important thing"
  acc_lim_x: 0.25                   
  acc_lim_theta: !degrees 15.0      

# Set the velocity limits of the robot
  max_vel_x: 0.45                   
  min_vel_x: 0.25                  
  max_vel_theta: !degrees 45.0      
  min_vel_theta: !degrees -45.0               
  min_in_place_vel_theta: !degrees 45.0 
# Notice that this velocity is set to be negative. A bit confusing admittedly.
  escape_vel: -0.0                 # -0.1

  holonomic_robot: false            # true

# ---- Goal tolerance parameters
  yaw_goal_tolerance: 0.25           # 0.25 rad = ~15 degree 
  xy_goal_tolerance: 0.1           # 0.2
  latch_xy_goal_tolerance: true     # false  -- If goal tolerance is latched, if the robot ever reaches the goal xy location it will simply rotate in place, even if it ends up outside the goal tolerance while it is doing so.
  
# ---- Foward simulation parameters
# We'll configure how long and with what granularity we'll forward simulate trajectories  
  sim_time: 1.8                     # 1.6 -- setting it higher can result in slightly smoother trajectories
  sim_granularity: 0.025            # 0.025
  angular_sim_granularity: 0.025    # 0.025
  vx_samples: 10                    # 3
  vtheta_samples: 20                # 20


# ---- Parameters for scoring trajectories
  meter_scoring: true              # false -- distance in meter or cells
  pdist_scale: 0.6                # 
  gdist_scale: 0.8                  # 
  occdist_scale: 0.01               # 0.01 -- weighting how much controller should avoid obstacles
  heading_lookahead: 0.325          # 0.325
  heading_scoring: true            # false
  heading_scoring_timestep: 0.8     # 0.8 -- only with heading_scoring true
  dwa: true                         # true -- false if robot has low acceleration limits
  publish_cost_grid_pc: false        # false
  global_frame_id: odom             # odom

# --- Oscillation prevention parameters
  oscillation_reset_dist: 0.1      # 0.05
  prune_plan: true # Eat up the plan as the robot moves along it


# ############################################
#
# ############################################
DWAPlannerROS:
  acc_lim_th: 1.5
  acc_lim_x: 0.8
  acc_lim_y: 0.0

  max_vel_x: 1.5
  min_vel_x: 0.0

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_trans_vel: 1.5
  min_trans_vel: 0.1

  max_rot_vel: 2.0
  min_rot_vel: 0.4

  sim_time: 1.7
  sim_granularity: 0.025

  goal_distance_bias: 24.0
  path_distance_bias: 32.0
  occdist_scale: 0.01

  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.1

  forward_point_distance: 0.325

  scaling_speed: 1.0
  max_scaling_factor: 0.2

  vx_samples: 10
  vy_samples: 0
  vtheta_samples: 20

  sim_period: 0.1

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2

  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01

  meter_scoring: true
  publish_cost_grid: true


