l500_depth_sensor:
  visual_preset: 3
  laser_power: 80
  confidence_threshold: 0
  min_distance: 250
  receiver_gain: 12
  post_processing_sharpening: 2
  pre_processing_sharpening: 3
  receiver_gain: 12
  noise_filtering: 2
  digital_gain: 2

rgb_camera:
  power_line_frequency: 1
  global_time_enabled: true
  exposure: 100
  gain: 4096
  enable_auto_exposure: false