play_motion:
  controllers: [arm_controller, head_controller, torso_controller, gripper_controller]

  motions:
    home_old:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.25, 0.20, 0.35, -0.20, 1.94, -1.57, 1.37, -1.39]
        time_from_start: 0.5
      - positions: [0.18, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, -1.39]
        time_from_start: 4.0
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, -1.39]
        time_from_start: 7.0
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 9.0
      meta:
        name: Home
        usage: demo
        description: 'Go home'

    grasping:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint, gripper_finger_joint]
      points:
      - positions: [0.21, -0.74, -3.21, 2.29, 0.16, -0.12, 0.84, 0.02]
        time_from_start: 1.0
      meta:
        name: grasping
        usage: demo
        description: 'Go pre grasp'

    home:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.25, 0.20, 0.35, -0.20, 1.94, -1.57, 1.37, -1.39]
        time_from_start: 0.5
      - positions: [0.18, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, -1.39]
        time_from_start: 2.5
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, -1.39]
        time_from_start: 4.0
      meta:
        name: Home Fast
        usage: demo
        description: 'Go home'

    home_fast:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.25, 0.20, 0.35, -0.20, 1.94, -1.57, 1.37, -1.39]
        time_from_start: 0.5
      - positions: [0.18, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, -1.39]
        time_from_start: 2.5
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, -1.39]
        time_from_start: 4.0
      meta:
        name: Home Fast
        usage: demo
        description: 'Go home'

    unfold_arm:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.30, 0.21, 0.35, -0.2, 0.8, -1.57, 1.37, 0.0]
        time_from_start: 0.5
      - positions: [0.30, 0.21, -0.2, -2.2, 1.15, -1.57, 0.2, 0.0]
        time_from_start: 6.0
      meta:
        name: Unfold arm
        usage: demo
        description: 'unfold_arm'

    reach_floor:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.19, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      - positions: [0.19, 1.6, -0.55, -1.35, 1.40, -1.57, -0.07, 0.0]
        time_from_start: 3.0
      - positions: [0.16, 1.6, -0.55, 0, 1.03, -1.57, -0.07, 0.0]
        time_from_start: 7.0
      meta:
        name: Reach Floor
        usage: demo
        description: 'Reach floor'

    reach_max:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.10, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      - positions: [0.35, 0.9, 0.68, -3.16, 1.10, 2.05, 1.0, 0.0]
        time_from_start: 4.0
      - positions: [0.35, 0.9, 1.05, -3.45, 0.45, 2.05, 1.0, 0.0]
        time_from_start: 7.0
      meta:
        name: Reach Max
        usage: demo
        description: 'Reach max'

    prepare_grasp:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint']
      points:
      - positions: [0.34, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 3.0
      - positions: [0.34, -0.12, 0.47, -0.20, 1.56, -1.58, 0.25, 0.0]
        time_from_start: 8.5
      - positions: [0.34, -0.12, 0.47, -0.20, 1.56, 1.60, 0.25, 1.19]
        time_from_start: 10.5
      meta:
        name: Prepare Grasp
        usage: demo
        description: 'Prepare grasp position'

    inspect_surroundings:
      joints: ['head_1_joint', 'head_2_joint']
      points:
      - positions: [-1., -0.85]
        time_from_start: 1.5
      - positions: [-1., -0.85]
        time_from_start: 2.0
      - positions: [1., -0.85]
        time_from_start: 4.5
      - positions: [1., -0.85]
        time_from_start: 5.0
      - positions: [0., -0.85]
        time_from_start: 7.0
      meta:
        name: Inspect Surroundings
        usage: demo
        description: 'Inspect surroundings around the robot'



    #deprecated, use close
    close_gripper:
      joints: [gripper_finger_joint]
      points:
      - positions: [0.0]
        time_from_start: 0.5

    close:
      joints: [gripper_finger_joint]
      points:
      - positions: [0.0]
        time_from_start: 0.5
      meta:
        name: Close Gripper
        usage: demo
        description: 'Closes gripper'

    #deprecated, use close_half
    close_gripper_half:
      joints: [gripper_finger_joint]
      points:
      - positions: [0.012]
        time_from_start: 0.5

    close_half:
      joints: [gripper_finger_joint]
      points:
      - positions: [0.012]
        time_from_start: 0.5
      meta:
        name: Close Gripper Half
        usage: demo
        description: 'Closes gripper halfway'

    #deprecated, use open
    open_gripper:
      joints: [gripper_finger_joint]
      points:
      - positions: [0.0255]
        time_from_start: 0.5

    open:
      joints: [gripper_finger_joint]
      points:
      - positions: [0.0255]
        time_from_start: 0.5
      meta:
        name: Open Gripper
        usage: demo
        description: 'Open gripper'

    point:
      joints: [gripper_finger_joint]
      points:
      - positions: [0.0]
        time_from_start: 0.5
      meta:
        name: Point
        usage: demo
        description: 'Closes gripper to point to something'




    wave:
      joints: [arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint,
      arm_5_joint, arm_6_joint, arm_7_joint]
      points:
      - positions: [0.09, -0.679638896132783, -3.1087325315620733, 2.0882339360702575, -1.1201172410014792, -0.031008601325809293, -2.0]
        time_from_start: 0.0
      - positions: [0.09, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0]
        time_from_start: 1.0
      - positions: [0.09, -0.7231278283145929, -2.9385504456273295, 2.18, -1.1201355028397157, -0.031008601325809293, -2.04]
        time_from_start: 2.0
      - positions: [0.09, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0]
        time_from_start: 3.0
      meta:
        name: Wave
        usage: demo
        description: 'wave'

    pregrasp_weight:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.10, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      meta:
        name: Pregrasp Weight
        usage: demo
        description: 'Pregrasp weight'

    do_weights:
      joints: [arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 2.0
      - positions: [1.6, -0.90, -3.16, 2.0, -1.57, 0.35, 0.0]
        time_from_start: 4.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 6.0
      - positions: [1.6, -0.90, -3.16, 2.0, -1.57, 0.35, 0.0]
        time_from_start: 8.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 10.0
      - positions: [1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 12.0
      meta:
        name: Do Weights
        usage: demo
        description: 'Do weights'




    #deprecated, use offer
    offer_gripper:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'gripper_finger_joint']
      points:
      - positions: [0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.62, -1.577, 0.0255]
        time_from_start: 0.0

    offer:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'gripper_finger_joint']
      points:
      - positions: [0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.62, -1.577, 0.0255]
        time_from_start: 0.0
      meta:
        name: Offer Gripper
        usage: demo
        description: 'Offer Gripper'

    shake_hands:
      joints: ['gripper_finger_joint', 'torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint']
      points:
      - positions: [0.0255, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 0.0
      - positions: [0.025, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 5.0
      - positions: [0.025, 0.296, 1.61, -0.93, -3.14, 1.40, -1.577, -0.2, -1.577]
        time_from_start: 6.0
      - positions: [0.025, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 7.0
      - positions: [0.025, 0.296, 1.61, -0.93, -3.14, 1.40, -1.577, -0.2, -1.577]
        time_from_start: 8.0
      - positions: [0.025, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 9.0
      - positions: [0.0255, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 11.0
      meta:
        name: Shake Hands
        usage: demo
        description: 'shake_hands'

    pick_from_floor:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'gripper_finger_joint']
      points:
      - positions: [0.226, 0.308, -0.695, -0.968, 1.582,  1.965, 0.273, -1.101, 0.0255]
        time_from_start: 0.0
      - positions: [0.12, 0.809, -1.197, -1.119, 0.322, 1.96, -0.849, 0.041, 0.0255]
        time_from_start: 4.0
      - positions: [0.12, 0.809, -1.197, -1.119, 0.345, 1.96, -0.849, 0.041, 0.0]
        time_from_start: 6.0
      - positions: [0.27, 0.21, -1.153, -1.538, 2.306, 1.965, 0.394, -0.082, 0.0]
        time_from_start: 9.0
      meta:
        name: Pick from floor
        usage: demo
        description: 'Pick a shirt-like object from floor in front of the robot'




    head_tour:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, 0]
        time_from_start: 0.1
      - positions: [0.7, 0]
        time_from_start: 3.0
      - positions: [0.7, 0.3]
        time_from_start: 6.0
      - positions: [0.7, -0.3]
        time_from_start: 9.0
      - positions: [0.7, 0.3]
        time_from_start: 12.0
      - positions: [-0.7, 0.3]
        time_from_start: 15.0
      - positions: [-0.7, -0.3]
        time_from_start: 18.0
      - positions: [0, 0]
        time_from_start: 21.0
      meta:
        name: Head Tour
        usage: demo
        description: 'head_tour'

    pointing_left:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      meta: {description: pointing_left, name: pointing_left, usage: demo}
      points:
      - positions: [0.19998590559757012, -1.339984962186872, -0.19954286766172208, 1.940211394560432, -1.5704734929417996, 0.10990430796763995, -1.390177870304425]
        time_from_start: 1.0

    pointing_home:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      meta: {description: pointing_home, name: pointing_home, usage: demo}
      points:
      - positions: [0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 1.0

    restaurant_carry:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      meta: {description: restaurant_carry, name: restaurant_carry, usage: demo}
      points:
      - positions: [0.20003192563162497, -1.3405832226295846, -0.19981234548359428, 1.9407329549463865, -1.5698799831991088, 1.3495498456874668, -1.39]
        time_from_start: 4.0

    restaurant_handover:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      meta: {description: restaurant_handover, name: restaurant_handover, usage: demo}
      points:
      - positions: [0.13873324027059786, -1.5007636211630797, -1.343287471655188, 1.6875307275767384, -1.5697704121696892, 1.3492987454117131, 0.7982477766211946]
        time_from_start: 4.0
