# parameters for padded robot (not used for self collision checks)
default_robot_padding: 0.03
default_robot_scale: 1.0
default_object_padding: 0.03
default_attached_padding: 0.02

default_robot_link_padding:
  cupro_finger_l_1_finger_link: 0.001
  cupro_finger_l_2_finger_link: 0.001
  cupro_finger_r_1_finger_link: 0.001
  cupro_finger_r_2_finger_link: 0.001