entities:
- name: test1
  type: misc/annotation
  pose: {x: 0, y: 1, zw: 2}
- name: test2
  type: misc/annotation
  pose: {x: 0, y: -1, zw: 0}
- name: test3
  type: misc/annotation
  pose: {x: 2, y: 2, zw: 1}

- name: arena
  parameter:
    room:
      - {x: -4, y: -4, z: 0}
      - {x: 4, y: -4, z: 0}
      - {x: 4, y: 4, z: 0}
      - {x: -4, y: 4, z: 0}

#- name: cam
#  type: testmodel/cam
#  pose: {x: 0.769996345043, y: 2.01848816872, zw: 0}