# Settings for both Costmaps

global_frame: map
robot_base_frame: base_footprint
robot_radius: 0.29
footprint_padding: 0.02

update_frequency : 5.0
publish_frequency: 5.0

transform_tolerance: 0.5. 

min_obstacle_height: -0.1
max_obstacle_height: 0.4

max_obstacle_range: 5.0
raytrace_range: 10
