# Independent settings for the planner's costmap
global_costmap:

  update_frequency : 2.5
  publish_frequency: 2.5

  #track_unknown_space: true
  #unknown_cost_value : 255

  resolution: 0.1

  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: obstacle_layer
      type: 'costmap_2d::CurrentObstacleLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'

  static_layer:
    enabled  : true
    subscribe_to_updates: true
    map_topic: /map

  obstacle_layer:
    enabled: true
    observation_sources: sensor_scan_clf
    combination_method: 0 # can erase static layer

    sensor_scan_clf:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: /scan_clf
      expected_update_rate: 2.0
      raytrace_range: 15.0
      obstacle_range: 8.0

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.7
    cost_scaling_factor: 15

