# Independent settings for the local costmap
local_costmap:

  update_frequency : 5.0
  publish_frequency: 2.0
  max_obstacle_height: 2

  static_map    : false
  rolling_window: true
  width         : 4.0
  height        : 4.0
  resolution    : 0.05

  plugins:
    - name: obstacle_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'


  obstacle_layer:
    enabled: true
    observation_sources: sensor_scan_clf #point_cloud_sensor1 point_cloud_sensor0
    #combination_method: 0 # can erase static layer
    #point_cloud_sensor0: {sensor_frame: xtion_link, data_type: PointCloud2, topic: /xtion/filtered/points, marking: true, clearing: false, min_obstacle_height: 0.05}
    #point_cloud_sensor1: {sensor_frame: xtion_link, data_type: PointCloud2, topic: /xtion/filtered/points, marking: false, clearing: true, min_obstacle_height: -1.0}

    sensor_scan_clf:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: /scan_clf
      expected_update_rate: 0.2
      #observation_persistence: 1.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 25.0
      obstacle_range: 8.0

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.55
    cost_scaling_factor: 5.0
