!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  footprint: '[]'
  footprint_padding: 0.01
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      footprint: '[]'
      footprint_padding: 0.01
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      height: 10
      id: 0
      name: Default
      origin_x: 0.0
      origin_y: 0.0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      publish_frequency: 2.5
      resolution: 0.1
      robot_radius: 0.275
      state: true
      transform_tolerance: 0.3
      type: ''
      update_frequency: 2.5
      width: 10
    state: []
  height: 10
  origin_x: 0.0
  origin_y: 0.0
  publish_frequency: 2.5
  resolution: 0.1
  robot_radius: 0.275
  transform_tolerance: 0.3
  update_frequency: 2.5
  width: 10
state: []
