# Independent settings for the planner's costmap
global_costmap:

  update_frequency : 2.5
  publish_frequency: 2.5

  #track_unknown_space: true
  #unknown_cost_value : 255

  resolution: 0.1

  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: obstacle_layer
      type: 'costmap_2d::ObstacleLayer'
      #    - name: footprint_layer
      #      type: 'costmap_2d::FootprintLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'

  static_layer:
    enabled  : true
    subscribe_to_updates: true
    map_topic: map

  obstacle_layer:
    enabled: true
    observation_sources: sensor_scan_clf
    #combination_method: 0 # can erase static layer

    sensor_scan_clf:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: /scan_clf
      expected_update_rate: 2.0
      #observation_persistence: 1.0
      #inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 15.0
      obstacle_range: 8.0

  #footprint_layer:
  #  enabled: true

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.3
    cost_scaling_factor: 2

### Biron
# commons
#max_obstacle_range: 3.0
#raytrace_range: 5.5

#inflation_radius: 0.90
#update_frequency: 5.0      # default 5.0
#publish_frequency: 5.0      # default 0.0
#cost_scaling_factor: 3.0    # default 10.0
  

