!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  acc_lim_theta: 1.2217304763960306
  acc_lim_x: 0.6
  acc_lim_y: 2.5
  angular_sim_granularity: 0.025
  dwa: false
  escape_reset_dist: 0.1
  escape_reset_theta: 1.57079632679
  escape_vel: -0.0
  gdist_scale: 4.85
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      acc_lim_theta: 1.2217304763960306
      acc_lim_x: 0.6
      acc_lim_y: 2.5
      angular_sim_granularity: 0.025
      dwa: false
      escape_reset_dist: 0.1
      escape_reset_theta: 1.57079632679
      escape_vel: -0.0
      gdist_scale: 4.85
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      heading_lookahead: 0.325
      heading_scale: 0.5
      heading_scoring: false
      heading_scoring_timestep: 0.8
      holonomic_robot: false
      id: 0
      max_vel_theta: 1.3962634015954636
      max_vel_x: 0.55
      max_vel_y: 0.55
      min_in_place_vel_theta: 0.7853981633974483
      min_vel_theta: -1.3962634015954636
      min_vel_x: 0.0
      min_vel_y: -0.55
      name: Default
      occdist_scale: 0.01
      oscillation_reset_dist: 0.1
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      pdist_scale: 2.0
      restore_defaults: false
      sim_granularity: 0.025
      sim_time: 1.6
      simple_attractor: false
      state: true
      type: ''
      vtheta_samples: 20
      vx_samples: 10
      vy_samples: 20
      y_vels: -0.3,-0.1,0.1,-0.3
    state: []
  heading_lookahead: 0.325
  heading_scale: 0.5
  heading_scoring: false
  heading_scoring_timestep: 0.8
  holonomic_robot: false
  max_vel_theta: 1.3962634015954636
  max_vel_x: 0.55
  max_vel_y: 0.55
  min_in_place_vel_theta: 0.7853981633974483
  min_vel_theta: -1.3962634015954636
  min_vel_x: 0.0
  min_vel_y: -0.55
  occdist_scale: 0.01
  oscillation_reset_dist: 0.1
  pdist_scale: 2.0
  restore_defaults: false
  sim_granularity: 0.025
  sim_time: 1.6
  simple_attractor: false
  vtheta_samples: 20
  vx_samples: 10
  vy_samples: 20
  y_vels: -0.3,-0.1,0.1,-0.3
state: []
